
# main.yml

# Workflow's name
name: Build TOMATOX For Win/Mac/Linux

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: |
          npm install && npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}